### ISSUE TITLE
Support bluelinelabs/Conductor

### ISSUE THREAD

**Issue by ervinmartirosyan** [6thsolution/EasyMVP#10]
https://github.com/bluelinelabs/Conductor
Conductor is great View-based approach but there view is wrapped in Controller. 
Add `Controller` annotation so `@Controller(layout = R.layout.my_view, presenter = MyPresenter.class)`

**Comment by SaeedMasoumi** [comment]
@ervinmartirosyan Do you mean, add `@Controller` annotation on controller class? 
```java
@Controller(layout = R.layout.my_view, presenter = MyPresenter.class)
public class HomeController extends Controller {
 
}
```

And EasyMVP should inflate layout and add `MyPresenter` to `HomeController` and dispatch its lifecycle?

**Comment by ervinmartirosyan** [comment]
Yes, you're right

**Comment by SaeedMasoumi** [comment]
@ervinmartirosyan Thanks, I will support this feature soon.

**Comment by mradzinski** [comment]
+1 on this. It's the only reason why I'm not using this instead of Mosby 😞
