### ISSUE TITLE
How to work with ButterKnife

### ISSUE THREAD

**Issue by znyang** [6thsolution/EasyMVP#11]
mudule-level:

`build.gradle`

```gradle
apply plugin: 'com.android.application'
apply plugin: 'easymvp'
apply plugin: 'android-apt'

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    compile 'com.jakewharton:butterknife:8.4.0'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'

    compile 'com.android.support:appcompat-v7:24.2.1'
}
```

the activity:

`MainActivity.java`

```java
@ActivityView(layout = R.layout.activity_main, presenter = MainPresenter.class)
public class MainActivity extends AppCompatActivity implements MainView{

    @Presenter
    MainPresenter mMainPresenter;

    @BindView(R.id.pb_loading)
    ProgressBar mPbLoading;

    @BindView(R.id.tv_content)
    TextView mTvContent;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        ButterKnife.bind(this);
    }
}
```

it doesn't work, and i can't find the _ViewDelegate class in `build/generated/source/apt/`.

**Comment by SaeedMasoumi** [comment]
EasyMVP automatically calls `setContentView` in `oncreate` method for you, so for supporting butterknife do this:
```java
@Override
    public void setContentView(@LayoutRes int layoutResID) {
        super.setContentView(layoutResID);
        ButterKnife.bind(this);
    }
```

for generated classes, Which version did you use? if you are on version `1.0.0` try to use `annotationProcessor` instead of `apt`, but it supports `apt` in `1.0.1`.

So try to clean and rebuild your project.

**Comment by SaeedMasoumi** [comment]
@znyang Take a look at [`SimpleActivity`](https://github.com/6thsolution/EasyMVP/blob/master/easymvp-test/src/main/java/com/sixthsolution/easymvp/test/SimpleActivity.java) test, it supports butterknife/

**Comment by znyang** [comment]
@SaeedMasoumi thanks. when i use `annotationProcessor` instead of `apt`, it works.

the plugin version is `1.0.1`

```gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'
        classpath 'com.sixthsolution.easymvp:easymvp-plugin:1.0.1'
    }
}
```

**Comment by SaeedMasoumi** [comment]
@znyang Oh i forgot to mention this part from [installation](https://github.com/6thsolution/EasyMVP#installation)

> There is no need for android-apt plugin for android gradle plugin version 2.2.0-alpha1 or higher. But if your are using it, please apply easymvp plugin after android-apt plugin.

```groovy
apply plugin: 'android-apt'
apply plugin: 'easymvp'
```
So just swap there positions
