### ISSUE TITLE
Make view null on onViewDetached

### ISSUE THREAD

**Issue by kratos23** [6thsolution/EasyMVP#12]
![default](https://cloud.githubusercontent.com/assets/12779215/20023975/70c137b2-a2f4-11e6-851a-75ffc58d48a8.PNG)

[Offical Guide](https://developer.android.com/reference/android/app/Activity.html)

If system kill app activity, onDestroy() may be will not cause, therefore onDestroyed will not cause too, therefore view link will be not null, and we will have memory leak.

**Comment by SaeedMasoumi** [comment]
@kratos23 all view references in `AbstractPresenter` and`_ViewDelegate` have been stored as `WeakReference`. Also in presenter, the view reference will be set to null on `onViewDetached`
