### ISSUE TITLE
Disable / remove getSupportLoaderManager() dependency ?

### ISSUE THREAD

**Issue by amallo** [6thsolution/EasyMVP#16]
Hi, your library looks amazing !

Is it possible to get rid of getSupportLoaderManager() dependency ? I need to extend an android.appActivity (third party library) and EasyMVP generates code that refer to the getSupportLoaderManager() method which cannot be resolved.

```java
private LoaderManager getLoaderManager(GVRMainActivity view) {
   return view.getSupportLoaderManager(); // Symbol not found
}
```

**Comment by amallo** [comment]
Thanks x 1000 !!

**Comment by SaeedMasoumi** [comment]
@amallo The new version will be uploaded soon(`1.0.4`),
