### ISSUE TITLE
No Demo

### ISSUE THREAD

**Issue by congxc** [6thsolution/EasyMVP#19]
No Demo？

**Comment by congxc** [comment]
No demo？

**Comment by xanderblinov** [comment]
@SaeedMasoumi is there any sample to try your library on?

**Comment by SaeedMasoumi** [comment]
@congxc @xanderblinov Sorry not yet, But I will upload a sample soon

For now you can take a look at [easymvp-test](https://github.com/6thsolution/EasyMVP/tree/master/easymvp-test) module

**Comment by mohamad-amin** [comment]
Hi @congxc @xanderblinov 
I've provided a sample application using [TV Maze API](http://tvmaze.com/api) showcasing some of the main features of this library.  It's written in kotlin and is under development yet.
You can check it out here:
https://github.com/mohamad-amin/CleanTvMaze

**Comment by SaeedMasoumi** [comment]
@mohamad-amin @congxc @xanderblinov I linked this sample app in readme file

**Comment by jeetdholakia** [comment]
It would be real helpful to have a demo written in java, covering two use cases and repository pattern.

**Comment by leonard2014** [comment]
Hi All,

This framework is really amazing. It's the best on the market. Just created a sample using Java, You can check it out here https://github.com/leonard2014/tvProgram_android

**Comment by SaeedMasoumi** [comment]
@leonard2014 Thanks, I'm really grateful for that
I add your sample project in [README.md](https://github.com/6thsolution/EasyMVP#demo) file.
