### ISSUE TITLE
View still available in presenter after onStop Activity callback

### ISSUE THREAD

**Issue by xanderblinov** [6thsolution/EasyMVP#20]
According [table](https://github.com/6thsolution/EasyMVP#presenter) after onStop callback view should be detached from presenter, but it is still available.

I've made some easy [sample](https://github.com/xanderblinov/EasyMvpSample), check it please (see logcat)

**Comment by SaeedMasoumi** [comment]
Yes, the view will be garbage collected automatically after `Presenter#onViewDetached` so it's just a hook to know about detach state.

But you can clear the view reference in `onViewDetached` by creating a `BasePresenter` like [AbstractPresenter](https://github.com/6thsolution/EasyMVP/blob/master/easymvp-api/src/main/java/easymvp/AbstractPresenter.java) class and clear the view reference in `onViewDetached`
