### ISSUE TITLE
Support presenters for RecyclerView.Adapter

### ISSUE THREAD

**Issue by RiccardoM** [6thsolution/EasyMVP#21]
Right now there is now way to use the `@Presenter` annotation inside a class which extends from `RecyclerView.Adapter`, preventing the use of the library while working with this kind of objects. 
I think that this should be supported as adapters are becoming nowadays a major part of Android application, and having the possibility to divide the view and the model part inside them could lead to a great improvement of code quality.

## Possible solution
**Fragment class.**
```java
@FragmentView(
   presenter = FragmentWithAdapterPresenter.class,
   adapter = FragmentAdapter.class  // Tells the adapter class
)
public class FragmentWithAdapter extends Fragment implements FragmentView {
  @Presenter
  FragmentWithAdapterPresenter presenter;

  // Bind the adapter
  @Adapter
  FragmentAdapter adapter;

}
```

**Adapter class**
```java
@Adapter(presenter = FragmentAdapterPresenter.class)
public class FragmentAdapter extends AbstractMVPAdapter<FragmentView> implements AdapterView {
  @Presenter // Binds the presenter to the adapter
  FragmentAdapterPresenter presenter;

  private FragmentView view;

  // Called after Fragment#onCreateView(), Activity#onCreate() or View#onDraw() has finished
  @Override
  protected void onViewAttached(View view){
    this.view = view;
    super.onViewAttached(view);
  }
}
```

**AbstractMVPAdapter class**
```java
public abstract class AbstractMVPAdapter<V>{
  protected void onViewAttached(V view);  // Called when the Activity, Fragment or View gets created
  protected void onViewDetached();  // Called when the Activity, Fragment or View gets destroyed

  protected V getView();  // Returns the bound view
}
```

**FragmentAdapterPresenter class**
```java
public class FragmentAdapterPresenter extends BaseAdapterPresenter<AdapterView>{
  // Methods of a common presenter
}
```

**BaseAdapterPresenter class**
```java
public abstract class BaseAdapterPresenter<V>{
  Same methods as the actual AbstractPresenter
}
```

## How it works
**Note**. The following working mechanism will use `Activity`as a reference, but it may be also `Fragment` or even `View`.

Creation lifecycle.
1. When an `Activity` gets created, after the `onCreate()` method, it calls the `AbstractMVPAdapter#onViewAttached(V1 view)`, which stores a `WeakReference` to the interface that the activity implements (`V1`).

2. `AbstractMVPAdapter#onViewAttached(V1 view)` calls `BaseAdapterPresenter#onViewAttached(V2 view)`, which stores inside the adapter's presenter, a `WeakReference` to the interface that the adapter implements (`V2`).

Destruction lifecycle
1. When an `Activity` gets destroyed, after the `onDestroy()` method, it calls the `AbstractMVPAdapter#onViewDetached(V1 view)`, which deletes the `WeakReference` to the interface implemented by the activity (`V1`).
2. Before destroying the `WeakReference` to `V1`, `AbstractMVPAdapter#onViewDetached(V1 view)` calls `BaseAdapterPresenter#onViewAttached(V2 view)` which tells the adapter's presenter to delete the `WeakReference` to `V2`, which is the view interface implemented by the adapter.

## Conclusions
Following this path should garantee that each component (activity, adapter and the adapter's presenter) is separated and does not depend on its dependencies. Also, when the `Activity` gets destroyed, it triggers the deletion of all its dependencies and the dependencies' dependencies too, avoiding memory leaks.

**Comment by SaeedMasoumi** [comment]
@RiccardoM Thanks for you feedback. I will support this feature soon.

**Comment by mehdok** [comment]
@RiccardoM I don't think that you need a separate `Presenter` for any Adapter, the Adapter is part of your fragment or activity, you can have a listener that communicate with you activities (or fragments) Presenter.
so at the end you reach a cleaner code with less class and codes.
