### ISSUE TITLE
Support Jack Transform API

### ISSUE THREAD

**Issue by SaeedMasoumi** [6thsolution/EasyMVP#23]
It seems that google finally supports jack transform api [[related issue](https://code.google.com/p/android/issues/detail?id=210730)]

**Comment by mohamad-amin** [comment]
@SaeedMasoumi  I don't think its needed as [google said](https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html) that the Jack toolchain is now deprecated Java 8 will be supported directly.

**Comment by SaeedMasoumi** [comment]
@mohamad-amin It's time to say wtf are you doing google :/
