### ISSUE TITLE
A question about ButterKnife

### ISSUE THREAD

**Issue by bptx0114** [6thsolution/EasyMVP#24]
I added  compile 'com.jakewharton:butterknife:8.5.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1' to my application module, and called method         ButterKnife.bind(this); in method onCreate,but widgets is still null, how could solution it?

**Comment by kratos23** [comment]
Did you add anotations to views?

**Comment by SaeedMasoumi** [comment]
It's not an EasyMVP problem, please post on butterknife's issue tracker
