### ISSUE TITLE
Presenter in injected too late

### ISSUE THREAD

**Issue by RiccardoM** [6thsolution/EasyMVP#26]
Nowadays the `Presenter` class is injected only inside the `Fragment#onResume()` method, which is really late inside the Fragments' life cycle.  
As the presenter should be used to tell what to show inside the view, it should be injected before `Fragment#onCreateView()` so that we can use it inside that method to define the view we want to display.

**Comment by SaeedMasoumi** [comment]
@RiccardoM I think it's not possible due to the limitation of `Loader`
