### ISSUE TITLE
 ButterKnife.bind(this); is Caused by: java.lang.IllegalStateException: Required view 'base_layout' with ID 2131427412 for field 'view' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) 。。。。

### ISSUE THREAD

**Issue by mirsfang** [6thsolution/EasyMVP#30]
ButterKnife.bind(this);   Should be called in onStar

**Comment by SaeedMasoumi** [comment]
@mirsfang it's not an EasyMVP related bug, Maybe you give a wrong id or call `bind` too soon.
Please see this [example](https://github.com/6thsolution/EasyMVP/blob/master/easymvp-test/src/main/java/com/sixthsolution/easymvp/test/SimpleActivity.java#L32)
