### ISSUE TITLE
In Presenter using (Activity)getView().getContext() occasionally reporting null pointer errors

### ISSUE THREAD

**Issue by mirsfang** [6thsolution/EasyMVP#31]
In Presenter using (Activity)getView().getContext() occasionally reporting null pointer errors，What is the reason，please ， thanks

**Comment by SaeedMasoumi** [comment]
@mirsfang Presenter is a pure java class, so it _must_ not know anything about android, like context, activity or whatever. furthermore you can test your presenters just with junit.  This is one of the advantages of separating logics using MVP.

Read this [part](https://github.com/6thsolution/EasyMVP#usage) again. `getView()` will return the interface you implemented in your `Activity`, `Fragment` or `CustomView`. In this example, `getView()` will return `MyView`, so it's not an instance of `Activity`.

Also using android dependencies in your presenters is an anti-pattern, I recommend you read this [blog post](https://8thlight.com/blog/uncle-bob/2012/08/13/the-clean-architecture.html) too.
