### ISSUE TITLE
easymvp-rx2-api not uploaded to bintray

### ISSUE THREAD

**Issue by mohamad-amin** [6thsolution/EasyMVP#32]
I think the new commit hasn't yet been uploaded to jCenter: http://jcenter.bintray.com/com/sixthsolution/easymvp/
Also, I think the Rx2 api shoild have FlowableUse case for backpressure related use cases.
Thanks.

**Comment by SaeedMasoumi** [comment]
@mohamad-amin including the package in jcenter takes one or two days at least
