### ISSUE TITLE
Mocking views in presenter testing

### ISSUE THREAD

**Issue by mohamad-amin** [6thsolution/EasyMVP#38]
When writing unit tests I can't change the view object in the presenter without calling `onViewAttached`
I think it would be nice if there was a method (with `@VisibleForTesting` annotation maybe) to change the view object of the presenter without calling any extra method.
This way we can easily mock views in presenter objects and write unit tests for any presenter and test them separately like MVP pattern suggests.
P.s: RxJava 2 API hasn't been uploaded to jcenter yet: http://jcenter.bintray.com/com/sixthsolution/easymvp/

**Comment by mohamad-amin** [comment]
I've provided a sample presenter test here:
https://github.com/mohamad-amin/CleanTvMaze/blob/develop/presentation-layer/src/test/java/com/mohamadamin/cleantvmaze/page/main/MainPresenterTest.kt

**Comment by SaeedMasoumi** [comment]
@mohamad-amin Do you need something (e.g. ``@VisibleForTesting``) that call ``mainPresenter.onViewAttached(mainView)`` automatically for you?

**Comment by mohamad-amin** [comment]
@SaeedMasoumi 
It is possible, but I think it makes it somehow confusing.
If we want to test each class independently, then we should be able test the presenter independently from view and vice versa.
Btw I think you got me wrong on `@VisibleForTesting`, I meant this annotation:
https://developer.android.com/reference/android/support/annotation/VisibleForTesting.html

It would be nice if we had a method like `setView(View view)` in presenter that was only visible for testing and not in main source set (using the `@VisibleForTesting` annotation we can make such methods I think).
This way we could easily mock the view and test the presenter independently.

**Comment by SaeedMasoumi** [comment]
@mohamad-amin This is not the responsibility of EasyMVP, because there are different ways to test your presenters in an isolated environment, hence you can implement your own ‍‍‍‍`Presenter` to provide your needed methods.
