### ISSUE TITLE
[Discussion] Improving @PresenterId annotation

### ISSUE THREAD

**Issue by RiccardoM** [6thsolution/EasyMVP#39]
From the last comment on #28:

> @RiccardoM Thanks, EasyMVP calls `getLoaderManager().initLoader(ID, ... , ... );` method, by default the ID is a [simple counter object](https://github.com/6thsolution/EasyMVP/blob/master/easymvp-compiler/src/main/java/easymvp/compiler/generator/decorator/BaseDecorator.java#L126) so when you create multiple instances of a class it will assign same id to them. There will be better solutions maybe, I think it can be simplified with putting ids in Bundle, but i encountered some bugs in custom Views.

What about using [UUID](https://developer.android.com/reference/java/util/UUID.html)s as the presenteres' id?  

Instead of passing the presenter id to its constructor and then associating it to the `@PresenterId` annotated object, a solution I came up with would be to have the same annotation (i.e. `@Presenter`) with a new boolean parameter (let's say `keepInstance`) that will act as follows:
* if `keepInstance` is set to `true`, no action will be taken, and everything will be the same;
* if `keepInstance` is set to `false`, the presenter id will be generated each time that a new instance of the view is created, using `UUID.randomUUID().toString().replace("-", "");`

I think that the resulting code inside the generator class would be something along the lines of this:
```java
if (keepInstance) {
     presenterId = LOADER_ID.incrementAndGet() + "";
} else {
    presenterId = "view." + UUID.randomUUID().toString().replace("-", "");
}
```

This method shouldn't have problem with custom views or stuff like that, as the UUID is indipendent from the object that creates it.

What are your thoughts on this solution @SaeedMasoumi?

**Comment by SaeedMasoumi** [comment]
@RiccardoM Sounds good, **but**

EasyMVP calls `loaderManager.initLoader(id,..)` in each Activity, Fragment , View or Conductor Controller.
By default for each view, the `id` is a hard coded generated integer (`LOADER_ID.incrementAndGet()`), For example `loaderManager.initLoader(500,..)`, so loader manager can distinguish assigned loader to this view from others.
In some situation that we need multiple instances of a same view class in an Activity or Fragment, we need to assign unique id to each instance.  for example an activity has two `MyCustomView` as its children, So we should assign for example `id = 100` to first view and `id = 200` to second one. But important thing is when the activity is recreated we need to assign `id = 100` to first view again and `id = 200` to second one too, So loader can preserve Presenter.

So who can we find proper ids in configuration changes when we use multiple instances of a class? 

Easiest solution is using `@PresenterId`,  So we can change our `initLoader` method to  `loaderManager.initLoader(view.presenterId,..)`

So as you see UUID will not work.
Maybe this solution will work:
```java
if(alreadyHasIdInBundle()) {
    loaderManager.initLoader(IdFromBundle(),..)
} else {
    id = generateAUniqueId()
    putIdIntoBundle(id)
    loaderManager.initLoader(id,..)
}
```
