### ISSUE TITLE
Forgetting @FragmentView makes Gradle crash without any error

### ISSUE THREAD

**Issue by rmontagnin** [6thsolution/EasyMVP#41]
**Bug**
If you forget the `@FragmentView` on a Fragment class, but you annotate with `@Presenter` a field, Gradle will crash while compiling without giving any error.

**How to replicate**
**1.** Create the following class
```java
public class MyFragment extent Fragment extends MyView {
    @Presenter MyPresenter presenter;

}
```
where `MyPresenter` and `MyView` are the presenter and view of this fragment. 

**2.** Try to build the project.

**Verified behaviour** 
The build craches telling `Cannot write ( null ) `

**Expected behaviour**
Throw some kind of exception

**Comment by SaeedMasoumi** [comment]
@RiccardoM  It's not a bug, It's an expected behavior, but I forgot to show a better error message.
