### ISSUE TITLE
请教下那个CI script怎么用的？

### ISSUE THREAD

**Issue by leerduo** [6thsolution/EasyMVP#9]

**Comment by SaeedMasoumi** [comment]
@leerduo  Can you ask your question in english?

**Comment by bachhuberdesign** [comment]
”请教下那个CI script怎么用的？“ - I would like to ask, how to use that CI script? (I'm assuming he's referring to [https://github.com/6thsolution/EasyMVP/blob/master/.script/ci.sh](https://github.com/6thsolution/EasyMVP/blob/master/.script/ci.sh))

**Comment by SaeedMasoumi** [comment]
@bachhuberdesign Thank you for your response
